jobs:
    - deployment: Deploy
      displayName: 'Deploy AWS'
      environment: $
      strategy:
          runOnce:
              deploy:
                  steps:
                      - task: CodeDeployDeployApplication@1
                        displayName: 'Deploy AWS EC2'
                        inputs:
                            awsCredentials: 'aws-php'
                            regionName: 'eu-central-1'
                            applicationName: 'azure-devops-php'
                            deploymentGroupName: 'azure-devops-php'
                            deploymentRevisionSource: 'workspace'
                            revisionBundle: $(System.DefaultWorkingDirectory)/**/*.zip
                            fileExistsBehavior: 'OVERWRITE'