jobs:
    - deployment: Deploy
      displayName: 'Deploy AWS'
      environment: $
      strategy:
          runOnce:
              deploy:
                  steps:
                      - task: CodeDeployDeployApplication@1
                        inputs:
                          awsCredentials: 'aws-php'
                          regionName: 'eu-central-1'
                          applicationName: 'azure-devops-php'
                          deploymentGroupName: 'azure-devops-php'
                          deploymentRevisionSource: 'workspace'
                          revisionBundle: '$(Pipeline.Workspace)/drop/azure-devops-php.zip'
                          bucketName: 'azure-devops-php'
                          fileExistsBehavior: 'OVERWRITE'