jobs:
  - deployment: Deploy
    displayName: 'Deploy to Azure App Service'
    environment: $
    pool:
        vmImage: 'Ubuntu 16.04'
    strategy:
        runOnce:
            deploy:
                steps:
                    - task: AzureWebApp@1
                      displayName: 'Deploy'
                      inputs:
                          azureSubscription: 'azure-devops-php'
                          appName: 'azure-devops-php'
                          package: $(Pipeline.Workspace)/drop/azure-devops-php.zip