jobs:
    - deployment: Deploy
      displayName: 'Deploy AWS'
      environment: $
      strategy:
          runOnce:
              deploy:
                  steps:
                      - task: S3Upload@1
                        inputs:
                          awsCredentials: 'aws-php'
                          regionName: 'eu-central-1'
                          bucketName: 'azure-devops-php'
                          globExpressions: '**'